package main

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/SirNacou/serverless-secure-share/internal/models"
	"github.com/SirNacou/serverless-secure-share/internal/utils"
	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
)

var ErrNameTaken = errors.New("Display name already taken")

type ProfileResponse struct {
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
}

type UpdateProfileRequest struct {
	DisplayName   string `json:"display_name"`
	AutoGenerated bool   `json:"auto_generated"`
}

type ProfileItem struct {
	Username    string `dynamodbav:"username"`
	DisplayName string `dynamodbav:"display_name"`
	UpdatedAt   int64  `dynamodbav:"updated_at"`
}

type App struct {
	dbClient              *dynamodb.Client
	profileTableName      string
	displayNamesTableName string
}

func newApp(ctx context.Context) (*App, error) {
	cfg, err := config.LoadDefaultConfig(ctx)
	if err != nil {
		return nil, fmt.Errorf("unable to load AWS config: %w", err)
	}

	return &App{
		dbClient:              dynamodb.NewFromConfig(cfg),
		profileTableName:      os.Getenv("PROFILE_TABLE_NAME"),
		displayNamesTableName: os.Getenv("DISPLAY_NAMES_TABLE_NAME"),
	}, nil
}

func extractUsername(event events.APIGatewayV2HTTPRequest) string {
	if event.RequestContext.Authorizer != nil && event.RequestContext.Authorizer.JWT != nil {
		if username, ok := event.RequestContext.Authorizer.JWT.Claims["username"]; ok {
			return username
		}
	}
	return ""
}

func validateDisplayName(name string) string {
	trimmed := strings.TrimSpace(name)
	if len(trimmed) < 1 {
		return "Display name cannot be empty"
	}
	if len(trimmed) > 50 {
		return "Display name must be 50 characters or less"
	}
	return ""
}

func randomSuffix() string {
	b := make([]byte, 3)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)[:4]
}

func (a *App) claimDisplayName(ctx context.Context, displayName, username string) error {
	if a.displayNamesTableName == "" {
		return nil
	}

	_, err := a.dbClient.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(a.displayNamesTableName),
		Item: map[string]types.AttributeValue{
			"display_name": &types.AttributeValueMemberS{Value: strings.ToLower(displayName)},
			"username":     &types.AttributeValueMemberS{Value: username},
		},
		ConditionExpression: aws.String("attribute_not_exists(display_name)"),
	})
	if err != nil {
		var condFailed *types.ConditionalCheckFailedException
		if errors.As(err, &condFailed) {
			return ErrNameTaken
		}
		return err
	}
	return nil
}

func (a *App) releaseDisplayName(ctx context.Context, displayName string) {
	if a.displayNamesTableName == "" || displayName == "" {
		return
	}

	_, err := a.dbClient.DeleteItem(ctx, &dynamodb.DeleteItemInput{
		TableName: aws.String(a.displayNamesTableName),
		Key: map[string]types.AttributeValue{
			"display_name": &types.AttributeValueMemberS{Value: strings.ToLower(displayName)},
		},
		ConditionExpression: aws.String("attribute_exists(display_name)"),
	})
	if err != nil {
		var condFailed *types.ConditionalCheckFailedException
		if !errors.As(err, &condFailed) {
			log.Printf("Failed to release display name '%s': %v", displayName, err)
		}
	}
}

func (a *App) fetchCurrentDisplayName(ctx context.Context, username string) (string, error) {
	result, err := a.dbClient.GetItem(ctx, &dynamodb.GetItemInput{
		TableName: aws.String(a.profileTableName),
		Key: map[string]types.AttributeValue{
			"username": &types.AttributeValueMemberS{Value: username},
		},
	})
	if err != nil {
		return "", err
	}

	if len(result.Item) == 0 {
		return "", nil
	}

	var profile ProfileItem
	if err := attributevalue.UnmarshalMap(result.Item, &profile); err != nil {
		return "", err
	}

	return profile.DisplayName, nil
}

func (a *App) saveProfile(ctx context.Context, username, displayName string) error {
	now := time.Now().Unix()
	_, err := a.dbClient.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(a.profileTableName),
		Item: map[string]types.AttributeValue{
			"username":     &types.AttributeValueMemberS{Value: username},
			"display_name": &types.AttributeValueMemberS{Value: displayName},
			"updated_at":   &types.AttributeValueMemberN{Value: strconv.FormatInt(now, 10)},
		},
	})
	return err
}

func (a *App) handleGet(ctx context.Context, username string) (events.APIGatewayV2HTTPResponse, error) {
	displayName, err := a.fetchCurrentDisplayName(ctx, username)
	if err != nil {
		log.Printf("Get profile error: %v", err)
		return utils.JsonResponse(500, models.ErrorResponse{Error: "Internal server error"})
	}

	return utils.JsonResponse(200, ProfileResponse{
		Username:    username,
		DisplayName: displayName,
	})
}

func (a *App) handlePut(ctx context.Context, username, body string) (events.APIGatewayV2HTTPResponse, error) {
	var req UpdateProfileRequest
	if err := json.Unmarshal([]byte(body), &req); err != nil {
		return utils.JsonResponse(400, models.ErrorResponse{Error: "Invalid JSON request body"})
	}

	if valErr := validateDisplayName(req.DisplayName); valErr != "" {
		return utils.JsonResponse(400, models.ErrorResponse{Error: valErr})
	}

	trimmed := strings.TrimSpace(req.DisplayName)
	oldDisplayName, err := a.fetchCurrentDisplayName(ctx, username)
	if err != nil {
		log.Printf("Fetch old profile error: %v", err)
		return utils.JsonResponse(500, models.ErrorResponse{Error: "Internal server error"})
	}

	if oldDisplayName == trimmed {
		return utils.JsonResponse(200, ProfileResponse{Username: username, DisplayName: trimmed})
	}

	finalName := trimmed

	if req.AutoGenerated {
		attempt := trimmed
		claimed := false
		maxAttempts := 5

		for i := 0; i < maxAttempts; i++ {
			err := a.claimDisplayName(ctx, attempt, username)
			if err == nil {
				claimed = true
				finalName = attempt
				break
			}
			if !errors.Is(err, ErrNameTaken) {
				log.Printf("Auto-claim display name error: %v", err)
				return utils.JsonResponse(500, models.ErrorResponse{Error: "Internal server error"})
			}
			attempt = fmt.Sprintf("%s_%s", trimmed, randomSuffix())
		}

		if !claimed {
			return utils.JsonResponse(409, models.ErrorResponse{Error: "Unable to generate a unique display name"})
		}
	} else {
		if err := a.claimDisplayName(ctx, trimmed, username); err != nil {
			if errors.Is(err, ErrNameTaken) {
				return utils.JsonResponse(409, models.ErrorResponse{Error: "Display name already taken"})
			}
			log.Printf("Manual claim display name error: %v", err)
			return utils.JsonResponse(500, models.ErrorResponse{Error: "Internal server error"})
		}
	}

	a.releaseDisplayName(ctx, oldDisplayName)

	if err := a.saveProfile(ctx, username, finalName); err != nil {
		log.Printf("Save profile error: %v", err)
		return utils.JsonResponse(500, models.ErrorResponse{Error: "Internal server error"})
	}

	return utils.JsonResponse(200, ProfileResponse{
		Username:    username,
		DisplayName: finalName,
	})
}

func (a *App) HandleRequest(ctx context.Context, event events.APIGatewayV2HTTPRequest) (events.APIGatewayV2HTTPResponse, error) {
	username := extractUsername(event)
	if username == "" {
		return utils.JsonResponse(401, models.ErrorResponse{Error: "Unauthorized"})
	}

	switch event.RequestContext.HTTP.Method {
	case "GET":
		return a.handleGet(ctx, username)
	case "PUT":
		return a.handlePut(ctx, username, event.Body)
	default:
		return utils.JsonResponse(405, models.ErrorResponse{Error: "Method not allowed"})
	}
}

func main() {
	ctx := context.Background()
	app, err := newApp(ctx)
	if err != nil {
		log.Fatalf("Failed to initialize application: %v", err)
	}

	lambda.Start(app.HandleRequest)
}
