/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TestRouteImport } from './routes/test'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedHistoryRouteImport } from './routes/_protected/history'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedShareRouteImport } from './routes/_protected/share'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as SShareIdRouteImport } from './routes/s/$shareId'
import { Route as ProtectedShareIndexRouteImport } from './routes/_protected/share/index'
import { Route as ProtectedShareCreateRouteImport } from './routes/_protected/share/create'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHistoryRoute = ProtectedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedShareRoute = ProtectedShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SShareIdRoute = SShareIdRouteImport.update({
  id: '/s/$shareId',
  path: '/s/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedShareIndexRoute = ProtectedShareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedShareRoute,
} as any)
const ProtectedShareCreateRoute = ProtectedShareCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ProtectedShareRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/history': typeof ProtectedHistoryRoute
  '/profile': typeof ProtectedProfileRoute
  '/share': typeof ProtectedShareRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/s/$shareId': typeof SShareIdRoute
  '/share/create': typeof ProtectedShareCreateRoute
  '/share/': typeof ProtectedShareIndexRoute
}
export interface FileRoutesByTo {
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/history': typeof ProtectedHistoryRoute
  '/profile': typeof ProtectedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/s/$shareId': typeof SShareIdRoute
  '/': typeof ProtectedIndexRoute
  '/share/create': typeof ProtectedShareCreateRoute
  '/share': typeof ProtectedShareIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/_protected/history': typeof ProtectedHistoryRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/share': typeof ProtectedShareRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/s/$shareId': typeof SShareIdRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/share/create': typeof ProtectedShareCreateRoute
  '/_protected/share/': typeof ProtectedShareIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/login'
    | '/test'
    | '/history'
    | '/profile'
    | '/share'
    | '/auth/callback'
    | '/s/$shareId'
    | '/share/create'
    | '/share/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/explore'
    | '/login'
    | '/test'
    | '/history'
    | '/profile'
    | '/auth/callback'
    | '/s/$shareId'
    | '/'
    | '/share/create'
    | '/share'
  id:
    | '__root__'
    | '/_protected'
    | '/explore'
    | '/login'
    | '/test'
    | '/_protected/history'
    | '/_protected/profile'
    | '/_protected/share'
    | '/auth/callback'
    | '/s/$shareId'
    | '/_protected/'
    | '/_protected/share/create'
    | '/_protected/share/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  TestRoute: typeof TestRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  SShareIdRoute: typeof SShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/history': {
      id: '/_protected/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ProtectedHistoryRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/share': {
      id: '/_protected/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ProtectedShareRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shareId': {
      id: '/s/$shareId'
      path: '/s/$shareId'
      fullPath: '/s/$shareId'
      preLoaderRoute: typeof SShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/share/': {
      id: '/_protected/share/'
      path: '/'
      fullPath: '/share/'
      preLoaderRoute: typeof ProtectedShareIndexRouteImport
      parentRoute: typeof ProtectedShareRoute
    }
    '/_protected/share/create': {
      id: '/_protected/share/create'
      path: '/create'
      fullPath: '/share/create'
      preLoaderRoute: typeof ProtectedShareCreateRouteImport
      parentRoute: typeof ProtectedShareRoute
    }
  }
}

interface ProtectedShareRouteChildren {
  ProtectedShareCreateRoute: typeof ProtectedShareCreateRoute
  ProtectedShareIndexRoute: typeof ProtectedShareIndexRoute
}

const ProtectedShareRouteChildren: ProtectedShareRouteChildren = {
  ProtectedShareCreateRoute: ProtectedShareCreateRoute,
  ProtectedShareIndexRoute: ProtectedShareIndexRoute,
}

const ProtectedShareRouteWithChildren = ProtectedShareRoute._addFileChildren(
  ProtectedShareRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedHistoryRoute: typeof ProtectedHistoryRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedShareRoute: typeof ProtectedShareRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedHistoryRoute: ProtectedHistoryRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedShareRoute: ProtectedShareRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  TestRoute: TestRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SShareIdRoute: SShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
