import { DeleteItemCommand, DynamoDBClient, GetItemCommand, PutItemCommand } from "@aws-sdk/client-dynamodb";
import { randomBytes } from "node:crypto";

const dynamoClient = new DynamoDBClient({ region: process.env.AWS_REGION || "ap-southeast-1" });
const PROFILE_TABLE_NAME = process.env.PROFILE_TABLE_NAME;
const DISPLAY_NAMES_TABLE_NAME = process.env.DISPLAY_NAMES_TABLE_NAME;

function corsHeaders() {
	return {
		"Content-Type": "application/json",
		"Access-Control-Allow-Origin": "*",
	};
}

function errorResponse(statusCode, message) {
	return {
		statusCode,
		headers: corsHeaders(),
		body: JSON.stringify({ error: message }),
	};
}

function successResponse(body) {
	return {
		statusCode: 200,
		headers: corsHeaders(),
		body: JSON.stringify(body),
	};
}

function validateDisplayName(name) {
	if (typeof name !== "string") return "Display name must be a string";
	const trimmed = name.trim();
	if (trimmed.length < 1) return "Display name cannot be empty";
	if (trimmed.length > 50) return "Display name must be 50 characters or less";
	return null;
}

function randomSuffix() {
	return randomBytes(3).toString("hex").slice(0, 4);
}

async function claimDisplayName(displayName, username) {
	if (!DISPLAY_NAMES_TABLE_NAME) return null;

	try {
		await dynamoClient.send(
			new PutItemCommand({
				TableName: DISPLAY_NAMES_TABLE_NAME,
				Item: {
					display_name: { S: displayName.toLowerCase() },
					username: { S: username },
				},
				ConditionExpression: "attribute_not_exists(display_name)",
			}),
		);
		return null;
	} catch (err) {
		if (err.name === "ConditionalCheckFailedException") {
			return "Display name already taken";
		}
		throw err;
	}
}

async function releaseDisplayName(displayName) {
	if (!DISPLAY_NAMES_TABLE_NAME || !displayName) return;

	try {
		await dynamoClient.send(
			new DeleteItemCommand({
				TableName: DISPLAY_NAMES_TABLE_NAME,
				Key: {
					display_name: { S: displayName.toLowerCase() },
				},
				ConditionExpression: "attribute_exists(display_name)",
			}),
		);
	} catch (err) {
		if (err.name !== "ConditionalCheckFailedException") throw err;
	}
}

function generateNameFromEmail(email) {
	if (!email) return null;
	const localPart = email.split("@")[0];
	return localPart.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 40);
}

export const handler = async (event) => {
	try {
		const claims = event.requestContext?.authorizer?.jwt?.claims;
		const username = claims?.username;
		const email = claims?.email;

		if (!username) {
			return errorResponse(401, "Unauthorized");
		}

		const method = event.requestContext?.http?.method;

		if (method === "GET") {
			const result = await dynamoClient.send(
				new GetItemCommand({
					TableName: PROFILE_TABLE_NAME,
					Key: {
						username: { S: username },
					},
				}),
			);

			const displayName = result.Item?.display_name?.S || null;

			return successResponse({ username, display_name: displayName });
		}

		if (method === "PUT") {
			const body = JSON.parse(event.body || "{}");
			const displayName = body.display_name;
			const autoGenerated = body.auto_generated === true;

			const validationError = validateDisplayName(displayName);
			if (validationError) {
				return errorResponse(400, validationError);
			}

			const trimmed = displayName.trim();
			const currentProfile = await dynamoClient.send(
				new GetItemCommand({
					TableName: PROFILE_TABLE_NAME,
					Key: { username: { S: username } },
				}),
			);
			const oldDisplayName = currentProfile.Item?.display_name?.S || null;

			// If the name hasn't changed, just return success
			if (oldDisplayName === trimmed) {
				return successResponse({ username, display_name: trimmed });
			}

			if (autoGenerated) {
				// Try the base name, append random suffix if taken
				let attempt = trimmed;
				const maxAttempts = 5;
				for (let i = 0; i < maxAttempts; i++) {
					const err = await claimDisplayName(attempt, username);
					if (!err) break;
					if (i === maxAttempts - 1) {
						return errorResponse(409, "Unable to generate a unique display name");
					}
					attempt = `${trimmed}_${randomSuffix()}`;
				}
				// Release old display name if it existed
				await releaseDisplayName(oldDisplayName);
				const finalName = attempt;
				await dynamoClient.send(
					new PutItemCommand({
						TableName: PROFILE_TABLE_NAME,
						Item: {
							username: { S: username },
							display_name: { S: finalName },
							updated_at: { N: Math.floor(Date.now() / 1000).toString() },
						},
					}),
				);
				return successResponse({ username, display_name: finalName });
			}

			// Manual save — enforce uniqueness
			const claimError = await claimDisplayName(trimmed, username);
			if (claimError) {
				return errorResponse(409, claimError);
			}

			await releaseDisplayName(oldDisplayName);

			await dynamoClient.send(
				new PutItemCommand({
					TableName: PROFILE_TABLE_NAME,
					Item: {
						username: { S: username },
						display_name: { S: trimmed },
						updated_at: { N: Math.floor(Date.now() / 1000).toString() },
					},
				}),
			);

			return successResponse({ username, display_name: trimmed });
		}

		return errorResponse(405, "Method not allowed");
	} catch (error) {
		console.error("Profile error:", error);
		return errorResponse(500, "Internal server error");
	}
};
