/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedHistoryRouteImport } from './routes/_protected/history'
import { Route as ProtectedExploreRouteImport } from './routes/_protected/explore'
import { Route as ProtectedShareIndexRouteImport } from './routes/_protected/share/index'
import { Route as ProtectedShareShareIdRouteImport } from './routes/_protected/share/$shareId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHistoryRoute = ProtectedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedExploreRoute = ProtectedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedShareIndexRoute = ProtectedShareIndexRouteImport.update({
  id: '/share/',
  path: '/share/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedShareShareIdRoute = ProtectedShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/explore': typeof ProtectedExploreRoute
  '/history': typeof ProtectedHistoryRoute
  '/share/$shareId': typeof ProtectedShareShareIdRoute
  '/share/': typeof ProtectedShareIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/explore': typeof ProtectedExploreRoute
  '/history': typeof ProtectedHistoryRoute
  '/': typeof ProtectedIndexRoute
  '/share/$shareId': typeof ProtectedShareShareIdRoute
  '/share': typeof ProtectedShareIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/explore': typeof ProtectedExploreRoute
  '/_protected/history': typeof ProtectedHistoryRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/share/$shareId': typeof ProtectedShareShareIdRoute
  '/_protected/share/': typeof ProtectedShareIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/explore'
    | '/history'
    | '/share/$shareId'
    | '/share/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/explore' | '/history' | '/' | '/share/$shareId' | '/share'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/explore'
    | '/_protected/history'
    | '/_protected/'
    | '/_protected/share/$shareId'
    | '/_protected/share/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/history': {
      id: '/_protected/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ProtectedHistoryRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/explore': {
      id: '/_protected/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ProtectedExploreRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/share/': {
      id: '/_protected/share/'
      path: '/share'
      fullPath: '/share/'
      preLoaderRoute: typeof ProtectedShareIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/share/$shareId': {
      id: '/_protected/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ProtectedShareShareIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedExploreRoute: typeof ProtectedExploreRoute
  ProtectedHistoryRoute: typeof ProtectedHistoryRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedShareShareIdRoute: typeof ProtectedShareShareIdRoute
  ProtectedShareIndexRoute: typeof ProtectedShareIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedExploreRoute: ProtectedExploreRoute,
  ProtectedHistoryRoute: ProtectedHistoryRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedShareShareIdRoute: ProtectedShareShareIdRoute,
  ProtectedShareIndexRoute: ProtectedShareIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
