/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as SShareIdRouteImport } from './routes/s/$shareId'
import { Route as ProtectedHistoryRouteImport } from './routes/_protected/history'
import { Route as ProtectedActiveRouteImport } from './routes/_protected/active'
import { Route as ProtectedShareIndexRouteImport } from './routes/_protected/share/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const SShareIdRoute = SShareIdRouteImport.update({
  id: '/s/$shareId',
  path: '/s/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedHistoryRoute = ProtectedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedActiveRoute = ProtectedActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedShareIndexRoute = ProtectedShareIndexRouteImport.update({
  id: '/share/',
  path: '/share/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/active': typeof ProtectedActiveRoute
  '/history': typeof ProtectedHistoryRoute
  '/s/$shareId': typeof SShareIdRoute
  '/share/': typeof ProtectedShareIndexRoute
}
export interface FileRoutesByTo {
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/active': typeof ProtectedActiveRoute
  '/history': typeof ProtectedHistoryRoute
  '/s/$shareId': typeof SShareIdRoute
  '/': typeof ProtectedIndexRoute
  '/share': typeof ProtectedShareIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/_protected/active': typeof ProtectedActiveRoute
  '/_protected/history': typeof ProtectedHistoryRoute
  '/s/$shareId': typeof SShareIdRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/share/': typeof ProtectedShareIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/login'
    | '/active'
    | '/history'
    | '/s/$shareId'
    | '/share/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/explore'
    | '/login'
    | '/active'
    | '/history'
    | '/s/$shareId'
    | '/'
    | '/share'
  id:
    | '__root__'
    | '/_protected'
    | '/explore'
    | '/login'
    | '/_protected/active'
    | '/_protected/history'
    | '/s/$shareId'
    | '/_protected/'
    | '/_protected/share/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  SShareIdRoute: typeof SShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/s/$shareId': {
      id: '/s/$shareId'
      path: '/s/$shareId'
      fullPath: '/s/$shareId'
      preLoaderRoute: typeof SShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/history': {
      id: '/_protected/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ProtectedHistoryRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/active': {
      id: '/_protected/active'
      path: '/active'
      fullPath: '/active'
      preLoaderRoute: typeof ProtectedActiveRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/share/': {
      id: '/_protected/share/'
      path: '/share'
      fullPath: '/share/'
      preLoaderRoute: typeof ProtectedShareIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedActiveRoute: typeof ProtectedActiveRoute
  ProtectedHistoryRoute: typeof ProtectedHistoryRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedShareIndexRoute: typeof ProtectedShareIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedActiveRoute: ProtectedActiveRoute,
  ProtectedHistoryRoute: ProtectedHistoryRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedShareIndexRoute: ProtectedShareIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  SShareIdRoute: SShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
